# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Syed Tousif Ahmed - Computer Engineer
email: stahmed@seas.upenn.edu
description: > # this means to ignore newlines until "baseurl:"
  Syed Tousif Ahmed is a PhD Student in Electrical and Systems Engineering at UPenn.
  Syed's interests lie in high performance computing, machine 
  intelligence, digital logic design, compilers and cryptography. Syed worked on 
  several production and startup machine intelligence teams such as 
  NVIDIA, NextDroid LLC, and Ahold USA. He has contributed to several 
  open source frameworks such as PyTorch and TensorFlow. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://syed-ahmed.github.io"
logo: /images/profile-pic1.jpg
permalink: /posts/:categories/:year/:month/:day/:title:output_ext
#baseurl: /~sxa1056
# Build settings
markdown: kramdown
twitter:
  username: tousifsays
social:
  name: Syed Tousif Ahmed
  links:
    - https://twitter.com/tousifsays
    - https://www.facebook.com/tousif111
    - https://www.linkedin.com/in/mrsyed
    - https://github.com/syed-ahmed

plugins:
  - jekyll-seo-tag
